name: local-dev-compose

services:
  mysql:
    container_name: mysql
    image: mysql:9
    restart: no
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-local
      TZ: 'Asia/Seoul'

    volumes:
      - ./local/mysql:/var/lib/mysql