spring.jpa.hibernate.ddl-auto: create

db:
  host: localhost
  username: root
  password: root
  database: db-local
  port: 3306
  url: jdbc:mysql://${db.host}:${db.port}/${db.database}

spring:
  ai:
    vectorstore:
      weaviate:
        scheme: http
        host: localhost:8081
        object-class: DrawerFile